### ISSUE TITLE
Bug xóa hết note đã lưu

### ISSUE THREAD

**Issue by zjpg** [lesongvi/Notevn-Tracker#1]
Khi nhấp vào xóa 1 note thì những note còn lại đều bị ẩn và màn hình hiện lên "Bạn chưa tạo note nào..."
Khi tim 1 note khác thì note cũ hiện lên lại.

**Comment by nguyenmauchanh** [comment]
@lesongvi sửa lỗi nè anh bạn.

**Comment by lesongvi** [comment]
fixed
